#!/bin/sh

# use lunarvim/neovim from vim if present
if [[ -x "$(command -v lvim)" ]]; then
  alias vim='lvim'
  alias vimdiff='lvim -d'
elif [[ -x "$(command -v nvim)" ]]; then
  alias vim='nvim'
  alias vimdiff='nvim -d'
fi

# sudo not required for some system commands
for command in mount umount pacman updatedb su systemctl; do
  alias $command="sudo $command"
done; unset command

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

alias dotfiles='git --git-dir=$HOME/.dotwsl/ --work-tree=$HOME'
alias tmp='cd /tmp'                                                 # go to /tmp quickly
alias dws='cd $HOME/Development'
alias zed='vim $ZDOTDIR/.zshrc'                                     # edit .zshrc quickly
alias zea='vim $ZDOTDIR/aliases'
alias zef='vim $ZDOTDIR/functions'
alias zre='source $ZDOTDIR/.zshrc'                                  # source .zshrc quickly
alias led='vim $XDG_CONFIG_HOME/lvim/config.lua'
alias ted='vim $XDG_CONFIG_HOME/tmux/tmux.conf'
alias pip='python -m pip'                                           # install python modules correctly
#alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'           # XDG BASE DIRECTORY wget
alias clear="printf '\033[2J\033[3J\033[1;1H'"                      # clear with no scrollback
alias locate='plocate --ignore-case'
alias lg='lazygit'
alias gs='git status'
alias gl='git log'
alias glo='git log --oneline'
alias gp='git push'
alias gpu='git push -u origin main'
